from enum import IntEnum, auto


class Key(IntEnum):
    NONE = 0

    ESCAPE = auto()
    TAB = auto()
    BACKSPACE = auto()
    ENTER = auto()
    INSERT = auto()
    DELETE = auto()

    RIGHT = auto()
    LEFT = auto()
    DOWN = auto()
    UP = auto()
    HOME = auto()
    END = auto()

    SPACE = auto()
    EXCLAM = auto()
    QUOTEDBL = auto()
    HASH = auto()
    DOLLAR = auto()
    PERCENT = auto()
    AMPERSAND = auto()
    APOSTROPHE = auto()
    PARENLEFT = auto()
    PARENRIGHT = auto()
    ASTERISK = auto()
    PLUS = auto()
    COMMA = auto()
    MINUS = auto()
    PERIOD = auto()
    SLASH = auto()

    KEY_0 = auto()
    KEY_1 = auto()
    KEY_2 = auto()
    KEY_3 = auto()
    KEY_4 = auto()
    KEY_5 = auto()
    KEY_6 = auto()
    KEY_7 = auto()
    KEY_8 = auto()
    KEY_9 = auto()

    COLON = auto()
    SEMICOLON = auto()
    LESS = auto()
    EQUAL = auto()
    GREATER = auto()
    QUESTION = auto()
    AT = auto()

    A = auto()
    B = auto()
    C = auto()
    D = auto()
    E = auto()
    F = auto()
    G = auto()
    H = auto()
    I = auto()
    J = auto()
    K = auto()
    L = auto()
    M = auto()
    N = auto()
    O = auto()
    P = auto()
    Q = auto()
    R = auto()
    S = auto()
    T = auto()
    U = auto()
    V = auto()
    W = auto()
    X = auto()
    Y = auto()
    Z = auto()

    SHIFT = auto()
    CTRL = auto()
    ALT = auto()
